name: 手動実行で MP3→WAV 変換＆アップロード

on:
  workflow_dispatch:
    inputs:
      target_folder:
        description: 'アップロード先フォルダ名'
        required: false
        default: 'processed'

jobs:
  convert-and-push:
    runs-on: ubuntu-latest
    env:
      TARGET_DIR: ${{ github.event.inputs.target_folder }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run conversion
        run: |
          python convert_to_lossless.py -o "${{ env.TARGET_DIR }}"

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ env.TARGET_DIR }}/"
          if git diff --cached --quiet; then
            echo "No new files to commit."
          else
            git commit -m "Convert MP3→WAV to '${{ env.TARGET_DIR }}' ($(ls "${{ env.TARGET_DIR }}" | wc -l) tracks)"
            git push
          fi
